### ISSUE TITLE
Would you please update this for the latest OHOL?

### ISSUE THREAD

**Issue by MarkLindsay** [JustinLove/onelife-client-patches#1]
There may be more to updating for this recent release. Layman's reading of the OHOL git messages seems support has been added for mods. Which may mean other methods have depreciated? But this may only be in the context of adding/editing items. For real, I don't know.

**Comment by MarkLindsay** [comment]
Oh, maybe you had already. Anyway, it is now.
Thank you. You're client is the best!

**Comment by JustinLove** [comment]
Yep, didn't see the update for a day or so. Looks like the official mods are mostly visual object edits, which are pretty different from what I'm doing.
