### ISSUE TITLE
Defaulting to a server says download the latest version.

### ISSUE THREAD

**Issue by MarkLindsay** [JustinLove/onelife-client-patches#2]
If I uncheck the "use custom server", when I join the game it says "please download the latest version". I can check the box and join any server I'd like, bigserver2 included, but if I let it default I get the error.

**Comment by JustinLove** [comment]
I just ran the build updater and the build process thinks it's current. Maybe Jason did something weird with version numbers in a recent update?

**Comment by MarkLindsay** [comment]
Oh, I just noticed while trying to get this latest Jason update working, that this is a him problem, not a you problem. Sorry.

**Comment by MarkLindsay** [comment]
...well, I guess a me problem. I deleted all the files and started from scratch, and things seem to work.

I run pullAndBuildTestSystem.sh to update. And that's what I ran to build from scratch. I don't know.
